kind: Secret
apiVersion: v1
metadata:
  name: blockchain-secret
  namespace: test-openliberty-deploy
stringData:
  FABRIC_CONNECTION_PROFILE: |-
    {{connection_profile}}
  FABRIC_WALLET_CREDENTIALS: |-
    {{wallet_credentials}}  
data:
  FABRIC_CHANNEL: {{fabric_channel}}
  FABRIC_CONTRACT: {{fabric_contract}}
  FABRIC_DEFAULT_IDENTITY: {{fabric_default_identity}}
type: Opaque
